# お腹のボタン押下をシミュレート
POST http://localhost:3090/command HTTP/1.1
content-type: application/json

{
  "type": "cancel"
}

###

# speech-to-textをシミュレート
POST http://localhost:3090/debug-speech HTTP/1.1
content-type: application/json

{
  "payload": "宇宙"
}

###

# speech-to-textをシミュレート
POST http://localhost:3090/debug-speech HTTP/1.1
content-type: application/json

{
  "payload": "ファイナルアンサー"
}
