# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wave.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nwave.proto\x12\x04wave\"\x9e\x01\n\x08WaveUnit\x12\n\n\x02id\x18\x01 \x01(\x05\x12%\n\x06\x61\x63tion\x18\x02 \x01(\x0e\x32\x15.wave.WaveUnit.Action\x12\x0c\n\x04wave\x18\x03 \x01(\x0c\"Q\n\x06\x41\x63tion\x12\x12\n\x0e\x41\x43TION_UNKNOWN\x10\x00\x12\x0f\n\x0b\x41\x43TION_BODY\x10\x01\x12\x10\n\x0c\x41\x43TION_CLOSE\x10\x02\x12\x10\n\x0c\x41\x43TION_RESET\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wave_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WAVEUNIT']._serialized_start=21
  _globals['_WAVEUNIT']._serialized_end=179
  _globals['_WAVEUNIT_ACTION']._serialized_start=98
  _globals['_WAVEUNIT_ACTION']._serialized_end=179
# @@protoc_insertion_point(module_scope)
